# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/z_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/z_message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15proto/z_message.proto\"/\n\x0cMessageColor\x12\t\n\x01R\x18\x01 \x01(\r\x12\t\n\x01G\x18\x02 \x01(\r\x12\t\n\x01\x42\x18\x03 \x01(\r\"0\n\x0fSetColorMessage\x12\x1d\n\x06\x63olors\x18\x01 \x03(\x0b\x32\r.MessageColorb\x06proto3'
)




_MESSAGECOLOR = _descriptor.Descriptor(
  name='MessageColor',
  full_name='MessageColor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='R', full_name='MessageColor.R', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='G', full_name='MessageColor.G', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='B', full_name='MessageColor.B', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=72,
)


_SETCOLORMESSAGE = _descriptor.Descriptor(
  name='SetColorMessage',
  full_name='SetColorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='colors', full_name='SetColorMessage.colors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=122,
)

_SETCOLORMESSAGE.fields_by_name['colors'].message_type = _MESSAGECOLOR
DESCRIPTOR.message_types_by_name['MessageColor'] = _MESSAGECOLOR
DESCRIPTOR.message_types_by_name['SetColorMessage'] = _SETCOLORMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageColor = _reflection.GeneratedProtocolMessageType('MessageColor', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGECOLOR,
  '__module__' : 'proto.z_message_pb2'
  # @@protoc_insertion_point(class_scope:MessageColor)
  })
_sym_db.RegisterMessage(MessageColor)

SetColorMessage = _reflection.GeneratedProtocolMessageType('SetColorMessage', (_message.Message,), {
  'DESCRIPTOR' : _SETCOLORMESSAGE,
  '__module__' : 'proto.z_message_pb2'
  # @@protoc_insertion_point(class_scope:SetColorMessage)
  })
_sym_db.RegisterMessage(SetColorMessage)


# @@protoc_insertion_point(module_scope)
