/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev */

#include "proto/z_message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MessageColor, MessageColor, AUTO)


PB_BIND(SetColorMessage, SetColorMessage, 2)



